---
global:
cases:
- tt_members: MV Vagrant
  debian_ip: 192.168.1.17
  debian_username: vagrant
  debian_password: vagrant
- tt_members: MV Localhost
  debian_ip: localhost
  debian_username: vagrant
  debian_password: vagrant
