---
global:
cases:
- tt_members: MV Vagrant
  debian_ip: 192.168.1.17
  debian_port: 22
  debian_username: vagrant
  debian_password: vagrant
  debian_protocol: ssh
- tt_members: MV Localhost
  debian_ip: 127.0.0.1
  debian_username: vagrant
  debian_password: vagrant
  debian_protocol: ssh
